db: re-extract unstaged change check

diff --git a/scripts/release/finalize b/scripts/release/finalize
--- a/scripts/release/finalize
+++ b/scripts/release/finalize
@@ -10,7 +10,7 @@
 [ -n "$DEBUG" ] && set -x
 set -euo pipefail
 
-source "$(dirname "${BASH_SOURCE[0]}")/shared"
+source "$(dirname "${BASH_SOURCE[0]}")/check-working-dir"
 
 echo 'Checking variables'
   MERGE_FROM="${MERGE_FROM:-$(git branch --show-current)}"
@@ -82,4 +82,9 @@ echo 'Removing generated static assets'
   git rm -f ./{nomad,client}/structs/*.generated.go
 echo
 
-git_add_check # from source ./shared
+# there should be no stray unexpected changes
+if ! git diff --color=always --exit-code; then
+  git status
+  echo "::error::Unexpected changes left unstaged by finalize script"
+  exit 1
+fi
diff --git a/scripts/release/prepare b/scripts/release/prepare
--- a/scripts/release/prepare
+++ b/scripts/release/prepare
@@ -9,7 +9,7 @@
 [ -n "$DEBUG" ] && set -x
 set -euo pipefail
 
-source "$(dirname "${BASH_SOURCE[0]}")/shared"
+source "$(dirname "${BASH_SOURCE[0]}")/check-working-dir"
 
 echo 'Checking variables'
   # starting with a release line branch like 'release/A.B.x'
@@ -76,4 +76,10 @@ echo '::group::Generate static assets'
 echo '::endgroup::'
 echo
 
-git_add_check # from source ./shared
+# there should be no stray unexpected changes
+if ! git diff --color=always --exit-code; then
+  git status
+  echo "::error::Unexpected changes left unstaged by prepare script"
+  exit 1
+fi
+
